# Generated by Django 6.1 on 2026-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_artistico', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
